"""Create a complete project config from discovered facts and explicit decisions."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from touchstone.config import ConfigError, EngineName
from touchstone.discovery import ProjectDiscovery, discover_project
from touchstone.execution import Executor


@dataclass(frozen=True, slots=True)
class InitOptions:
    start: Path
    engine: EngineName
    model: str
    workflows: tuple[str, ...] = ()
    schedule: str = "hourly"
    output: Path | None = None
    force: bool = False
    discovered: ProjectDiscovery | None = None


def initialize(options: InitOptions, executor: Executor) -> Path:
    if not options.model.strip():
        raise ConfigError("init requires an explicit model")
    found = options.discovered or discover_project(options.start, executor)
    target = (options.output or found.root / "touchstone.toml").expanduser().resolve()
    if target.exists() and not options.force:
        raise ConfigError(f"configuration already exists at {target}; pass --force to replace it")
    target.parent.mkdir(parents=True, exist_ok=True)
    project_path = os.path.relpath(found.root, target.parent)
    text = render_config(options, found, project_path=project_path)
    temporary = target.with_name(f".{target.name}.tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(target)
    return target


def render_config(
    options: InitOptions, discovery: ProjectDiscovery, *, project_path: str = "."
) -> str:
    workflows = ", ".join(_quote(item) for item in options.workflows)
    return f"""\
# Generated by `touchstone init`. Relative paths resolve from this file.
version = 1

[project]
path = {_quote(project_path)}

[forge]
provider = "github"
slug = {_quote(discovery.slug)}
default_branch = {_quote(discovery.default_branch)}
required_workflows = [{workflows}]
escalation_label = "touchstone:needs-review"
reap_after_hours = 6

[engine]
name = {_quote(options.engine)}
model = {_quote(options.model)}
audit_effort = "high"
review_effort = "high"
timeout_seconds = 2700

[execution]
target = "local"

[loop.code]
brief = "builtin:code-audit"
label = "touchstone:audit"
schedule = {_quote(options.schedule)}
protected_paths = [".github/", ".env", ".env.*", "migrations/", "AGENTS.md"]

[loop.code.context]
project = "this repository and its data model"
ledger = "No project findings ledger is configured; treat the queue as empty."
protected = "the configured protected paths"
rules_clause = ""
"""


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


__all__ = ["InitOptions", "initialize", "render_config"]
