"""Drawing the graph, so the picture cannot drift from the code.

A diagram pasted into a README is a diagram that was true once. These render
from the compiled graph, so `touchstone graph --check` can fail CI when the
committed picture stops matching the edges — the same reason the census exists
for the rules.
"""

from __future__ import annotations

from pathlib import Path

from touchstone.graph import build

#: Where the committed diagram lives. Mermaid rather than an image: it is text,
#: so a diff shows which edge moved, and GitHub renders it in place.
DIAGRAM = Path("docs/graph.md")

_HEADER = """<!-- Generated by `touchstone graph --write`. Do not edit by hand. -->
# The loop, as the code defines it

```mermaid
"""

_FOOTER = """```

`park` is an interrupt, not an exit. The thread is checkpointed there and
resumes when a person answers on the pull request.
"""


def mermaid() -> str:
    """The graph as Mermaid source. No dependencies."""
    return build().compile().get_graph().draw_mermaid()


def ascii_art() -> str:
    """The graph as ASCII. Needs `grandalf`, which is why it is not the default."""
    return build().compile().get_graph().draw_ascii()


def png(path: Path) -> None:
    """Render to a file.

    Renders through mermaid.ink by default, which means a network call — worth
    knowing before putting this in a job that is supposed to work offline.
    """
    path.write_bytes(build().compile().get_graph().draw_mermaid_png())


def document() -> str:
    return f"{_HEADER}{mermaid()}{_FOOTER}"


def check(root: Path) -> tuple[bool, str]:
    """Whether the committed diagram still matches the graph."""
    target = root / DIAGRAM
    if not target.exists():
        return (False, f"{DIAGRAM} does not exist; run `touchstone graph --write`")
    if target.read_text(encoding="utf-8") != document():
        return (False, f"{DIAGRAM} is stale; run `touchstone graph --write`")
    return (True, f"{DIAGRAM} matches the graph")


def write(root: Path) -> Path:
    target = root / DIAGRAM
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(document(), encoding="utf-8")
    return target


__all__ = ["DIAGRAM", "ascii_art", "check", "document", "mermaid", "png", "write"]
