from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from touchstone.config import Config, ConfigError, HarnessConfig, load
from touchstone.harnesses import HarnessResolutionError, load_registry, resolve_harness


def _run(*argv: str, cwd: Path) -> str:
    completed = subprocess.run(argv, cwd=cwd, check=True, capture_output=True, text=True)
    return completed.stdout.strip()


def _config(tmp_path: Path, harness: HarnessConfig) -> Config:
    root = tmp_path / "target"
    (root / ".touchstone").mkdir(parents=True)
    (root / ".touchstone/generated.toml").write_text(
        """\
[metadata]
package_version = "0.1.2"
source_digest = "sha256:test"
[metadata.profile_versions]
""",
        encoding="utf-8",
    )
    external = (
        f'source = "{harness.source}"\nref = "{harness.ref}"\n'
        if harness.mode == "external"
        else ""
    )
    (root / "touchstone.toml").write_text(
        f'''\
version = 2
generated = ".touchstone/generated.toml"
[project]
path = "."
[forge]
slug = "acme/target"
[engine]
name = "codex"
model = "gpt-test"
[harness]
mode = "{harness.mode}"
entrypoint = "{harness.entrypoint}"
{external}
[loop.code]
brief = "builtin:code-audit"
label = "touchstone:audit"
''',
        encoding="utf-8",
    )
    return load(root / "touchstone.toml")


def _git_repository(path: Path, *, remote: str | None = None) -> str:
    path.mkdir(parents=True)
    _run("git", "init", "-b", "main", cwd=path)
    _run("git", "config", "user.name", "Test", cwd=path)
    _run("git", "config", "user.email", "test@example.invalid", cwd=path)
    if remote:
        _run("git", "remote", "add", "origin", remote, cwd=path)
    return path.as_posix()


def test_embedded_harness_resolves_generated_provenance(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    (config.repo_path / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; version=0.1.0 source=abc123 content=def456 -->\n",
        encoding="utf-8",
    )

    context = resolve_harness(config)

    assert context.mode == "embedded"
    assert context.source == "repository"
    assert context.entrypoint == (config.repo_path / "AGENTS.md").resolve()
    assert context.revision == "abc123"
    assert context.context_root == config.repo_path
    assert context.evidence == ("generated-source:abc123",)


def test_embedded_harness_can_resolve_from_fetched_run_worktree(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    (config.repo_path / "AGENTS.md").write_text("stale checkout rules\n", encoding="utf-8")
    worktree = tmp_path / "run-worktree"
    worktree.mkdir()
    (worktree / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; source=fetched123 -->\n", encoding="utf-8"
    )

    context = resolve_harness(config, target_checkout=worktree)

    assert context.context_root == worktree.resolve()
    assert context.revision == "fetched123"


def test_embedded_harness_reports_missing_entrypoint(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config)

    assert error.value.reason_code == "harness-entrypoint-missing"


def test_generated_embedded_harness_requires_parseable_source(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    (config.repo_path / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; version=0.1.0 -->\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config)

    assert error.value.reason_code == "harness-provenance-invalid"


def test_local_registry_rejects_noncanonical_source_identity(tmp_path: Path) -> None:
    path = tmp_path / "harnesses.toml"
    path.write_text(f'[harnesses.not-canonical]\npath = "{tmp_path}"\n', encoding="utf-8")

    with pytest.raises(ConfigError, match="canonical owner/repository"):
        load_registry(path)


def test_external_harness_resolves_a_clean_snapshot_from_named_revision(tmp_path: Path) -> None:
    bare = tmp_path / "acme/efficient-harness.git"
    bare.parent.mkdir()
    _run("git", "init", "--bare", "--initial-branch=main", str(bare), cwd=tmp_path)
    checkout = tmp_path / "efficient-harness"
    _git_repository(checkout, remote=str(bare))
    entrypoint = checkout / "harness/00-INDEX.md"
    entrypoint.parent.mkdir(parents=True)
    entrypoint.write_text("committed rules\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "rules", cwd=checkout)
    _run("git", "push", "-u", "origin", "main", cwd=checkout)
    revision = _run("git", "rev-parse", "HEAD", cwd=checkout)
    entrypoint.write_text("new local rules must not leak\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "local rules", cwd=checkout)
    local_head = _run("git", "rev-parse", "HEAD", cwd=checkout)
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/efficient-harness`.\n", encoding="utf-8"
    )

    context = resolve_harness(
        config,
        registry={"acme/efficient-harness": checkout},
        snapshot_root=tmp_path / "snapshots",
    )

    assert context.mode == "external"
    assert context.source == "acme/efficient-harness"
    assert context.revision == revision
    assert context.entrypoint.read_text(encoding="utf-8") == "committed rules\n"
    assert context.context_root.is_relative_to(tmp_path / "snapshots")
    assert not context.context_root.is_relative_to(config.repo_path)
    assert _run("git", "rev-parse", "HEAD", cwd=checkout) == local_head
    assert _run("git", "status", "--porcelain", cwd=checkout) == ""


def test_external_harness_remote_mismatch_is_typed(tmp_path: Path) -> None:
    checkout = tmp_path / "wrong-harness"
    _git_repository(checkout, remote="https://github.com/acme/wrong-harness.git")
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/efficient-harness`.\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config, registry={"acme/efficient-harness": checkout})

    assert error.value.reason_code == "harness-identity-mismatch"


def test_external_harness_requires_local_registration(tmp_path: Path) -> None:
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config, registry={})

    assert error.value.reason_code == "checkout-not-installed"
