from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from touchstone.config import Config, ConfigError, HarnessConfig, load
from touchstone.harnesses import HarnessResolutionError, load_registry, resolve_harness


def _run(*argv: str, cwd: Path) -> str:
    completed = subprocess.run(argv, cwd=cwd, check=True, capture_output=True, text=True)
    return completed.stdout.strip()


def _config(tmp_path: Path, harness: HarnessConfig, *, target: str = "local") -> Config:
    root = tmp_path / "target"
    (root / ".touchstone").mkdir(parents=True)
    (root / ".touchstone/generated.toml").write_text(
        """\
[metadata]
package_version = "0.1.2"
source_digest = "sha256:test"
[metadata.profile_versions]
""",
        encoding="utf-8",
    )
    external = (
        f'source = "{harness.source}"\nref = "{harness.ref}"\n'
        if harness.mode == "external"
        else ""
    )
    execution = (
        ""
        if target == "local"
        else (
            '[execution]\ntarget = "ssh"\n'
            '[execution.ssh]\nhost = "remote-host"\n'
            'workdir = "/srv/touchstone/work"\nstate_dir = "/srv/touchstone/state"\n'
        )
    )
    (root / "touchstone.toml").write_text(
        f'''\
version = 2
generated = ".touchstone/generated.toml"
[project]
path = "."
[forge]
slug = "acme/target"
[engine]
name = "codex"
model = "gpt-test"
[harness]
mode = "{harness.mode}"
entrypoint = "{harness.entrypoint}"
{external}
[loop.code]
brief = "builtin:code-audit"
label = "touchstone:audit"
{execution}''',
        encoding="utf-8",
    )
    return load(root / "touchstone.toml")


def _git_repository(path: Path, *, remote: str | None = None) -> str:
    path.mkdir(parents=True)
    _run("git", "init", "-b", "main", cwd=path)
    _run("git", "config", "user.name", "Test", cwd=path)
    _run("git", "config", "user.email", "test@example.invalid", cwd=path)
    if remote:
        _run("git", "remote", "add", "origin", remote, cwd=path)
    return path.as_posix()


def test_embedded_harness_resolves_generated_provenance(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    (config.repo_path / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; version=0.1.0 source=abc123 content=def456 -->\n",
        encoding="utf-8",
    )

    context = resolve_harness(config)

    assert context.mode == "embedded"
    assert context.source == "repository"
    assert context.entrypoint == (config.repo_path / "AGENTS.md").resolve()
    assert context.revision == "abc123"
    assert context.context_root == config.repo_path
    assert context.evidence == ("generated-source:abc123",)


def test_embedded_harness_can_resolve_from_fetched_run_worktree(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    (config.repo_path / "AGENTS.md").write_text("stale checkout rules\n", encoding="utf-8")
    worktree = tmp_path / "run-worktree"
    worktree.mkdir()
    (worktree / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; source=fetched123 -->\n", encoding="utf-8"
    )

    context = resolve_harness(config, target_checkout=worktree)

    assert context.context_root == worktree.resolve()
    assert context.revision == "fetched123"


def test_embedded_harness_reports_missing_entrypoint(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config)

    assert error.value.reason_code == "harness-entrypoint-missing"


def test_generated_embedded_harness_requires_parseable_source(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    (config.repo_path / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; version=0.1.0 -->\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config)

    assert error.value.reason_code == "harness-provenance-invalid"


def test_local_registry_rejects_noncanonical_source_identity(tmp_path: Path) -> None:
    path = tmp_path / "harnesses.toml"
    path.write_text(f'[harnesses.not-canonical]\npath = "{tmp_path}"\n', encoding="utf-8")

    with pytest.raises(ConfigError, match="canonical owner/repository"):
        load_registry(path)


def _offline_ssh(checkout: Path, bare: Path) -> None:
    """Serve a GitHub-shaped ssh remote from a local repository.

    `git remote get-url` reports where git will really go, `insteadOf` included, so a checkout
    cannot merely claim a GitHub URL. This answers as that host would, without a network.
    """

    script = checkout.parent / "offline-ssh.py"
    script.write_text(
        "#!/usr/bin/env python3\n"
        "import shlex\n"
        "import subprocess\n"
        "import sys\n"
        "argv = shlex.split(sys.argv[-1])\n"
        f"argv[-1] = {str(bare)!r}\n"
        "sys.exit(subprocess.run(argv).returncode)\n",
        encoding="utf-8",
    )
    script.chmod(0o755)
    _run("git", "config", "core.sshCommand", str(script), cwd=checkout)


def test_external_harness_resolves_a_clean_snapshot_from_named_revision(tmp_path: Path) -> None:
    bare = tmp_path / "acme/efficient-harness.git"
    bare.parent.mkdir()
    _run("git", "init", "--bare", "--initial-branch=main", str(bare), cwd=tmp_path)
    checkout = tmp_path / "efficient-harness"
    # The remote has to read as the GitHub repository it claims to be, because that is what the
    # resolver verifies — and `git remote get-url` applies `insteadOf`, so rewriting cannot fake
    # it. A stand-in ssh keeps the fetch local while the URL stays genuine.
    _git_repository(checkout, remote="git@github.com:acme/efficient-harness.git")
    _offline_ssh(checkout, bare)
    entrypoint = checkout / "harness/00-INDEX.md"
    entrypoint.parent.mkdir(parents=True)
    entrypoint.write_text("committed rules\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "rules", cwd=checkout)
    _run("git", "push", "-u", "origin", "main", cwd=checkout)
    revision = _run("git", "rev-parse", "HEAD", cwd=checkout)
    entrypoint.write_text("new local rules must not leak\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "local rules", cwd=checkout)
    local_head = _run("git", "rev-parse", "HEAD", cwd=checkout)
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/efficient-harness`.\n", encoding="utf-8"
    )

    context = resolve_harness(
        config,
        registry={"acme/efficient-harness": checkout},
        snapshot_root=tmp_path / "snapshots",
    )

    assert context.mode == "external"
    assert context.source == "acme/efficient-harness"
    assert context.revision == revision
    assert context.entrypoint.read_text(encoding="utf-8") == "committed rules\n"
    assert context.context_root.is_relative_to(tmp_path / "snapshots")
    assert not context.context_root.is_relative_to(config.repo_path)
    assert _run("git", "rev-parse", "HEAD", cwd=checkout) == local_head
    assert _run("git", "status", "--porcelain", cwd=checkout) == ""


def test_external_harness_remote_mismatch_is_typed(tmp_path: Path) -> None:
    checkout = tmp_path / "wrong-harness"
    _git_repository(checkout, remote="https://github.com/acme/wrong-harness.git")
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/efficient-harness`.\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config, registry={"acme/efficient-harness": checkout})

    assert error.value.reason_code == "harness-identity-mismatch"


def test_external_harness_requires_local_registration(tmp_path: Path) -> None:
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )

    with pytest.raises(HarnessResolutionError) as error:
        resolve_harness(config, registry={})

    assert error.value.reason_code == "checkout-not-installed"


class _RemoteExecutor:
    """Stands in for a machine that is not this one.

    Every path it is asked about is remote: nothing here touches the local filesystem, so a
    resolver that reaches for `Path` reports a missing entrypoint instead of reading this.
    """

    where = "ssh remote-host"
    replaces_environment = False

    def __init__(self, files: dict[str, str], revision: str = "remote999") -> None:
        self.files = files
        self.revision = revision
        self.commands: list[tuple[list[str], str | None]] = []

    def run(self, argv, *, cwd=None, timeout=None, stdin_null=True, env=None):  # type: ignore[no-untyped-def]
        from touchstone.execution import Result

        self.commands.append((list(argv), cwd))
        if argv[:3] == ["git", "rev-parse", "HEAD"]:
            return Result(code=0, stdout=f"{self.revision}\n", stderr="")
        if argv[:2] == ["test", "-L"]:
            return Result(code=1, stdout="", stderr="")
        if argv[:2] == ["test", "-f"]:
            return Result(code=0 if argv[2] in self.files else 1, stdout="", stderr="")
        return Result(code=1, stdout="", stderr="unexpected command")

    def read_text(self, path: str) -> str | None:
        return self.files.get(path)

    def write_text(self, path: str, text: str) -> None:  # pragma: no cover - unused here
        self.files[path] = text

    def exists(self, path: str) -> bool:
        return path in self.files


def test_embedded_harness_reads_the_target_through_its_executor(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    remote_root = "/srv/touchstone/run-worktree"
    executor = _RemoteExecutor(
        {f"{remote_root}/AGENTS.md": "<!-- Generated by Misoto Harness; source=remote123 -->\n"}
    )

    context = resolve_harness(config, target_checkout=Path(remote_root), executor=executor)

    assert context.context_root == Path(remote_root)
    assert context.entrypoint == Path(f"{remote_root}/AGENTS.md")
    assert context.revision == "remote123"


def test_embedded_harness_does_not_fall_back_to_the_local_filesystem(tmp_path: Path) -> None:
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    # The very path the run would inspect exists here, holding different content.
    decoy = tmp_path / "decoy"
    decoy.mkdir()
    (decoy / "AGENTS.md").write_text(
        "<!-- Generated by Misoto Harness; source=local666 -->\n", encoding="utf-8"
    )
    executor = _RemoteExecutor({})

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config, target_checkout=decoy, executor=executor)

    assert blocked.value.reason_code == "harness-entrypoint-missing"


def test_external_harness_checks_target_identity_through_its_executor(tmp_path: Path) -> None:
    checkout = Path(_git_repository(tmp_path / "harness", remote="git@github.com:acme/harness.git"))
    (checkout / "AGENTS.md").write_text("harness rules\n", encoding="utf-8")
    _run("git", "add", "AGENTS.md", cwd=checkout)
    _run("git", "commit", "-m", "rules", cwd=checkout)
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            entrypoint="AGENTS.md",
            source="acme/harness",
            ref="origin/main",
        ),
    )
    remote_root = "/srv/touchstone/run-worktree"
    executor = _RemoteExecutor({f"{remote_root}/AGENTS.md": "declares nothing\n"})

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(
            config,
            registry={"acme/harness": checkout},
            target_checkout=Path(remote_root),
            executor=executor,
        )

    assert blocked.value.reason_code == "harness-identity-mismatch"


def test_external_harness_refuses_a_session_that_cannot_read_the_snapshot(tmp_path: Path) -> None:
    """The snapshot is local; a session on another machine would run without its rules."""
    checkout = Path(_git_repository(tmp_path / "harness", remote="git@github.com:acme/harness.git"))
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            entrypoint="AGENTS.md",
            source="acme/harness",
            ref="origin/main",
        ),
        target="ssh",
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/harness`.\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config, registry={"acme/harness": checkout})

    assert blocked.value.reason_code == "harness-unreachable"


@pytest.mark.parametrize(
    "remote",
    [
        "https://evil.example/acme/harness.git",
        "git@evil.example:acme/harness.git",
        "ssh://git@evil.example/acme/harness.git",
        "https://github.example.com/acme/harness.git",
    ],
)
def test_external_harness_rejects_the_right_slug_on_the_wrong_host(
    tmp_path: Path, remote: str
) -> None:
    """The last two path segments are not an identity; the host is half of it."""
    checkout = Path(_git_repository(tmp_path / "harness", remote=remote))
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            entrypoint="AGENTS.md",
            source="acme/harness",
            ref="origin/main",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/harness`.\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config, registry={"acme/harness": checkout})

    assert blocked.value.reason_code == "harness-identity-mismatch"


def test_external_harness_rejects_a_local_path_remote(tmp_path: Path) -> None:
    """A local mirror cannot prove it is the GitHub repository it is registered as."""
    mirror = tmp_path / "acme/harness"
    checkout = Path(_git_repository(tmp_path / "checkout", remote=str(mirror)))
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            entrypoint="AGENTS.md",
            source="acme/harness",
            ref="origin/main",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/harness`.\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config, registry={"acme/harness": checkout})

    assert blocked.value.reason_code == "harness-identity-mismatch"


def test_external_harness_ignores_a_local_branch_shadowing_the_remote_ref(tmp_path: Path) -> None:
    """`origin/main` is a legal local branch name, and `git rev-parse` would prefer it."""
    bare = tmp_path / "acme/efficient-harness.git"
    bare.parent.mkdir()
    _run("git", "init", "--bare", "--initial-branch=main", str(bare), cwd=tmp_path)
    checkout = tmp_path / "efficient-harness"
    _git_repository(checkout, remote="git@github.com:acme/efficient-harness.git")
    _offline_ssh(checkout, bare)
    entrypoint = checkout / "harness/00-INDEX.md"
    entrypoint.parent.mkdir(parents=True)
    entrypoint.write_text("published rules\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "published", cwd=checkout)
    _run("git", "push", "-u", "origin", "main", cwd=checkout)
    published = _run("git", "rev-parse", "HEAD", cwd=checkout)

    # A local branch by that exact name, carrying different rules and never pushed.
    entrypoint.write_text("unpublished local rules\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "local only", cwd=checkout)
    _run("git", "branch", "origin/main", cwd=checkout)
    _run("git", "reset", "--hard", published, cwd=checkout)

    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness/00-INDEX.md",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/efficient-harness`.\n", encoding="utf-8"
    )

    context = resolve_harness(
        config,
        registry={"acme/efficient-harness": checkout},
        snapshot_root=tmp_path / "snapshots",
    )

    assert context.revision == published
    assert context.entrypoint.read_text(encoding="utf-8") == "published rules\n"


def test_embedded_harness_refuses_a_symlinked_entrypoint(tmp_path: Path) -> None:
    """A link is how host content becomes the project's rules."""
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    outside = tmp_path / "host-rules.md"
    outside.write_text("host content\n", encoding="utf-8")
    (config.repo_path / "AGENTS.md").symlink_to(outside)

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config)

    assert blocked.value.reason_code == "harness-identity-mismatch"


def test_embedded_harness_refuses_an_entrypoint_under_a_symlinked_directory(
    tmp_path: Path,
) -> None:
    """The escaping link need not be the last component."""
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="rules/AGENTS.md"))
    outside = tmp_path / "host-rules"
    outside.mkdir()
    (outside / "AGENTS.md").write_text("host content\n", encoding="utf-8")
    (config.repo_path / "rules").symlink_to(outside, target_is_directory=True)

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config)

    assert blocked.value.reason_code == "harness-identity-mismatch"


def test_embedded_harness_refuses_a_symlinked_entrypoint_on_a_remote_checkout() -> None:
    """The orchestrator cannot see the link, so the machine holding the checkout is asked."""

    class _LinkedRemote(_RemoteExecutor):
        def run(self, argv, *, cwd=None, timeout=None, stdin_null=True, env=None):  # type: ignore[no-untyped-def]
            from touchstone.execution import Result

            if argv[:2] == ["test", "-L"]:
                return Result(code=0, stdout="", stderr="")
            return super().run(argv, cwd=cwd, timeout=timeout, stdin_null=stdin_null, env=env)

    import tempfile

    with tempfile.TemporaryDirectory() as scratch:
        config = _config(Path(scratch), HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
        remote_root = "/srv/touchstone/run-worktree"
        executor = _LinkedRemote({f"{remote_root}/AGENTS.md": "host content\n"})

        with pytest.raises(HarnessResolutionError) as blocked:
            resolve_harness(config, target_checkout=Path(remote_root), executor=executor)

    assert blocked.value.reason_code == "harness-identity-mismatch"


def test_config_check_does_not_validate_the_orchestrator_for_a_remote_run(
    tmp_path: Path, capsys
) -> None:  # type: ignore[no-untyped-def]
    """A local entrypoint said `clean` for a checkout on another machine."""
    from touchstone.cli import main

    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"), target="ssh")
    # Present on this machine, which is exactly what must stop being the answer.
    (config.repo_path / "AGENTS.md").write_text("orchestrator rules\n", encoding="utf-8")

    exit_code = main(["--config", str(config.source.path), "config", "check", "--json"])

    assert exit_code == 3
    payload = json.loads(capsys.readouterr().out)
    assert payload["status"] == "blocked"


def test_embedded_harness_blocks_when_the_symlink_probe_cannot_answer(tmp_path: Path) -> None:
    """A dropped connection must not read like a passed containment check."""

    class _UnreachableProbe(_RemoteExecutor):
        def run(self, argv, *, cwd=None, timeout=None, stdin_null=True, env=None):  # type: ignore[no-untyped-def]
            from touchstone.execution import Result

            if argv[:2] == ["test", "-L"]:
                return Result(code=255, stdout="", stderr="ssh: connection closed")
            return super().run(argv, cwd=cwd, timeout=timeout, stdin_null=stdin_null, env=env)

    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    remote_root = "/srv/touchstone/run-worktree"
    executor = _UnreachableProbe(
        {f"{remote_root}/AGENTS.md": "<!-- Generated by Misoto Harness; source=remote123 -->\n"}
    )

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config, target_checkout=Path(remote_root), executor=executor)

    assert blocked.value.reason_code == "harness-unreachable"


def test_embedded_harness_blocks_when_the_symlink_probe_times_out(tmp_path: Path) -> None:
    class _TimingOutProbe(_RemoteExecutor):
        def run(self, argv, *, cwd=None, timeout=None, stdin_null=True, env=None):  # type: ignore[no-untyped-def]
            from touchstone.execution import Result

            if argv[:2] == ["test", "-L"]:
                return Result(code=1, stdout="", stderr="", timed_out=True)
            return super().run(argv, cwd=cwd, timeout=timeout, stdin_null=stdin_null, env=env)

    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="AGENTS.md"))
    remote_root = "/srv/touchstone/run-worktree"
    executor = _TimingOutProbe({f"{remote_root}/AGENTS.md": "rules\n"})

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config, target_checkout=Path(remote_root), executor=executor)

    assert blocked.value.reason_code == "harness-unreachable"


def test_embedded_harness_refuses_a_directory_entrypoint(tmp_path: Path) -> None:
    """A directory names no rules document."""
    config = _config(tmp_path, HarnessConfig(mode="embedded", entrypoint="harness"))
    (config.repo_path / "harness").mkdir()

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(config)

    assert blocked.value.reason_code == "harness-entrypoint-missing"


def test_external_harness_refuses_a_directory_entrypoint(tmp_path: Path) -> None:
    bare = tmp_path / "acme/efficient-harness.git"
    bare.parent.mkdir()
    _run("git", "init", "--bare", "--initial-branch=main", str(bare), cwd=tmp_path)
    checkout = tmp_path / "efficient-harness"
    _git_repository(checkout, remote="git@github.com:acme/efficient-harness.git")
    _offline_ssh(checkout, bare)
    (checkout / "harness").mkdir()
    (checkout / "harness/00-INDEX.md").write_text("rules\n", encoding="utf-8")
    _run("git", "add", ".", cwd=checkout)
    _run("git", "commit", "-m", "rules", cwd=checkout)
    _run("git", "push", "-u", "origin", "main", cwd=checkout)
    config = _config(
        tmp_path,
        HarnessConfig(
            mode="external",
            source="acme/efficient-harness",
            ref="origin/main",
            entrypoint="harness",
        ),
    )
    (config.repo_path / "AGENTS.md").write_text(
        "Shared Harness: canonical repo `acme/efficient-harness`.\n", encoding="utf-8"
    )

    with pytest.raises(HarnessResolutionError) as blocked:
        resolve_harness(
            config,
            registry={"acme/efficient-harness": checkout},
            snapshot_root=tmp_path / "snapshots",
        )

    assert blocked.value.reason_code == "harness-entrypoint-missing"
