#!/usr/bin/env python3
# Generated by Misoto Harness; DO NOT EDIT.
"""Self-contained validation for a public Harness project snapshot."""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
RULE_ID = re.compile(r"^(?:HAR|[A-Z][A-Z0-9]{1,11})-[A-Z][A-Z0-9]{1,11}-\d{3}$")
DECLARATION = re.compile(
    r"^- \*\*\[([^\]\n]+)\] (MUST|SHOULD|MAY) — (.+?)\.\*\* (\S.*)$", re.MULTILINE
)
LEVELS = {"MUST", "SHOULD", "MAY"}
STATUSES = {"draft", "active", "deprecated", "retired"}
LEGAL_STATUS_TRANSITIONS = {
    "draft": {"draft", "active"},
    "active": {"active", "deprecated"},
    "deprecated": {"deprecated", "retired"},
    "retired": {"retired"},
}
ENFORCEMENTS = {"prompt", "review", "lint", "test", "ci", "runtime", "manual"}
MARKER = "Generated by Misoto Harness; DO NOT EDIT."
MAX_HISTORY_COMMITS = 2048
MAX_HISTORY_PATHS = 128
MAX_HISTORY_OBJECTS = 32768
MAX_REGISTRY_BYTES = 2 * 1024 * 1024
MAX_HISTORY_BYTES = 64 * 1024 * 1024


class CheckError(ValueError):
    pass


def parse_json(text: str, label: str) -> dict[str, object]:
    def reject_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
        result: dict[str, object] = {}
        for key, value in pairs:
            if key in result:
                raise CheckError(f"duplicate JSON key in {label}: {key}")
            result[key] = value
        return result

    payload = json.loads(text, object_pairs_hook=reject_duplicates)
    if not isinstance(payload, dict):
        raise CheckError(f"JSON object required: {label}")
    return payload


def load_json(path: Path) -> dict[str, object]:
    return parse_json(path.read_text(encoding="utf-8"), str(path))


def source_scope(text: str, path: Path) -> str:
    if not text.startswith("---\n") or "\n---\n" not in text[4:]:
        raise CheckError(f"invalid source frontmatter: {path}")
    frontmatter = text[4 : text.find("\n---\n", 4)]
    values = [
        line.partition(":")[2].strip()
        for line in frontmatter.splitlines()
        if line.startswith("scope:")
    ]
    if len(values) != 1:
        raise CheckError(f"source requires one scope: {path}")
    return values[0]


def validate_contract(registry_path: Path, source_path: Path, expected_scope: str) -> None:
    payload = load_json(registry_path)
    if payload.get("schemaVersion") != 2:
        raise CheckError(f"registry must use schema version 2: {registry_path}")
    rules = payload.get("rules")
    if not isinstance(rules, list):
        raise CheckError(f"registry rules must be a list: {registry_path}")
    registered: dict[str, dict[str, object]] = {}
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            raise CheckError(f"invalid registry entry: {registry_path}")
        rule_id = rule["id"]
        if not RULE_ID.fullmatch(rule_id) or rule_id in registered:
            raise CheckError(f"invalid or duplicate rule id: {rule_id}")
        if rule.get("level") not in LEVELS or rule.get("scope") != expected_scope:
            raise CheckError(f"registry metadata mismatch: {rule_id}")
        required_text = ("name", "owner", "statement", "rationale", "since")
        sources = rule.get("sources")
        enforcement = rule.get("enforcement")
        if (
            any(not isinstance(rule.get(field), str) or not rule[field] for field in required_text)
            or rule.get("status") not in STATUSES
            or not isinstance(sources, list)
            or not sources
            or not all(
                isinstance(source, dict)
                and set(source) == {"type", "ref"}
                and source.get("type") in {"url", "policy"}
                and isinstance(source.get("ref"), str)
                and source["ref"]
                for source in sources
            )
            or not isinstance(enforcement, list)
            or not enforcement
            or not all(
                isinstance(entry, dict)
                and entry.get("kind") in ENFORCEMENTS
                and isinstance(entry.get("blocking"), bool)
                and (
                    not entry["blocking"]
                    or (isinstance(entry.get("check"), str) and entry["check"])
                )
                for entry in enforcement
            )
        ):
            raise CheckError(f"incomplete registry entry: {rule_id}")
        registered[rule_id] = rule

    text = source_path.read_text(encoding="utf-8")
    if source_scope(text, source_path) != expected_scope:
        raise CheckError(f"source scope mismatch: {source_path}")
    declarations = DECLARATION.findall(text)
    seen: dict[str, tuple[str, str, str]] = {}
    for rule_id, level, name, statement in declarations:
        if not RULE_ID.fullmatch(rule_id) or rule_id in seen:
            raise CheckError(f"invalid or duplicate source rule id: {rule_id}")
        seen[rule_id] = (level, name, statement)
    active = {rule_id for rule_id, rule in registered.items() if rule["status"] == "active"}
    if set(seen) != active:
        raise CheckError(f"registry/source rule mismatch: {registry_path}")
    for rule_id, (level, name, statement) in seen.items():
        if (
            registered[rule_id]["level"] != level
            or registered[rule_id]["name"] != name
            or registered[rule_id]["statement"] != statement
        ):
            raise CheckError(f"rule declaration mismatch: {rule_id}")


def validate_shared_contract() -> None:
    registry_path = ROOT / ".rulesync" / "shared-rules.json"
    payload = load_json(registry_path)
    if payload.get("schemaVersion") != 2:
        raise CheckError("shared registry must use schema version 2")
    rules = payload.get("rules")
    if not isinstance(rules, list):
        raise CheckError("shared registry rules must be a list")
    registered: dict[str, dict[str, object]] = {}
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            raise CheckError("invalid shared registry entry")
        rule_id = rule["id"]
        sources = rule.get("sources")
        enforcement = rule.get("enforcement")
        if not RULE_ID.fullmatch(rule_id) or rule_id in registered:
            raise CheckError(f"invalid or duplicate shared rule id: {rule_id}")
        if rule.get("scope") not in {"core", "stack"} or rule.get("level") not in LEVELS:
            raise CheckError(f"shared registry metadata mismatch: {rule_id}")
        if (
            any(
                not isinstance(rule.get(field), str) or not rule[field]
                for field in ("name", "owner", "statement", "rationale", "since")
            )
            or rule.get("status") not in STATUSES
            or not isinstance(sources, list)
            or not sources
            or not all(
                isinstance(source, dict)
                and set(source) == {"type", "ref"}
                and source.get("type") in {"url", "policy"}
                and isinstance(source.get("ref"), str)
                and source["ref"]
                for source in sources
            )
            or not isinstance(enforcement, list)
            or not enforcement
            or not all(
                isinstance(entry, dict)
                and entry.get("kind") in ENFORCEMENTS
                and isinstance(entry.get("blocking"), bool)
                and (
                    not entry["blocking"]
                    or (isinstance(entry.get("check"), str) and entry["check"])
                )
                for entry in enforcement
            )
        ):
            raise CheckError(f"incomplete shared registry entry: {rule_id}")
        registered[rule_id] = rule
    sources = sorted((ROOT / ".rulesync" / "rules").glob("[12]0-*.md"))
    sources += sorted((ROOT / ".rulesync" / "nested").glob("**/20-stack-*.md"))
    source_texts = {
        path.relative_to(ROOT).as_posix(): path.read_text(encoding="utf-8") for path in sources
    }
    validate_shared_projections(payload, registered, source_texts, str(registry_path))


def is_shared_source_path(relative: str) -> bool:
    name = relative.rsplit("/", 1)[-1]
    return (
        relative.startswith(".rulesync/rules/")
        and name.startswith(("10-core-", "20-stack-"))
        and re.fullmatch(r"[12]0-[a-z0-9][a-z0-9.-]*\.md", name) is not None
    ) or (
        relative.startswith(".rulesync/nested/")
        and name.startswith("20-stack-")
        and re.fullmatch(r"20-stack-[a-z0-9][a-z0-9.-]*\.md", name) is not None
        and re.fullmatch(
            r"(?:[a-z0-9][a-z0-9._-]*/)+20-stack-[a-z0-9][a-z0-9.-]*\.md",
            relative.removeprefix(".rulesync/nested/"),
        )
        is not None
    )


def projection_records(payload: dict[str, object], label: str) -> dict[str, frozenset[str]]:
    projections = payload.get("projections")
    if not isinstance(projections, dict) or not projections:
        raise CheckError(f"shared projections must be a non-empty object: {label}")
    records: dict[str, frozenset[str]] = {}
    for relative, rule_ids in projections.items():
        if (
            not isinstance(relative, str)
            or not is_shared_source_path(relative)
            or not isinstance(rule_ids, list)
            or not rule_ids
            or not all(
                isinstance(rule_id, str) and RULE_ID.fullmatch(rule_id) for rule_id in rule_ids
            )
            or len(set(rule_ids)) != len(rule_ids)
        ):
            raise CheckError(f"invalid shared projection: {relative}")
        records[relative] = frozenset(rule_ids)
    return records


def validate_shared_projections(
    payload: dict[str, object],
    registered: dict[str, dict[str, object]],
    source_texts: dict[str, str],
    label: str,
) -> None:
    projections = projection_records(payload, label)
    actual_sources = {relative for relative in source_texts if is_shared_source_path(relative)}
    if set(projections) != actual_sources:
        raise CheckError(f"shared projection path mismatch: {label}")
    occurrences: dict[str, str] = {}
    stack_memberships: dict[str, frozenset[str]] = {}
    for relative, expected_ids in projections.items():
        source_name = relative.rsplit("/", 1)[-1]
        expected_scope = "core" if source_name.startswith("10-core-") else "stack"
        text = source_texts[relative]
        if source_scope(text, Path(relative)) != expected_scope:
            raise CheckError(f"shared source scope mismatch: {relative}")
        declarations: dict[str, tuple[str, str, str]] = {}
        for rule_id, level, name, statement in DECLARATION.findall(text):
            if not RULE_ID.fullmatch(rule_id) or rule_id in declarations:
                raise CheckError(f"invalid or duplicate shared source rule id: {rule_id}")
            declarations[rule_id] = (level, name, statement)
        if set(declarations) != expected_ids:
            raise CheckError(f"shared projection rule mismatch: {relative}")
        if expected_scope == "stack":
            membership = frozenset(declarations)
            previous_membership = stack_memberships.get(source_name)
            if previous_membership is not None and previous_membership != membership:
                raise CheckError(f"shared stack projection mismatch: {relative}")
            stack_memberships[source_name] = membership
        for rule_id, (level, name, statement) in declarations.items():
            rule = registered.get(rule_id)
            if (
                rule is None
                or rule.get("status") != "active"
                or rule.get("scope") != expected_scope
                or rule.get("level") != level
                or rule.get("name") != name
                or rule.get("statement") != statement
            ):
                raise CheckError(f"shared registry mismatch: {rule_id}")
            previous_source = occurrences.get(rule_id)
            if previous_source is not None and not (
                expected_scope == "stack" and previous_source == source_name
            ):
                raise CheckError(f"duplicate shared source rule id: {rule_id}")
            occurrences[rule_id] = source_name
    active = {rule_id for rule_id, rule in registered.items() if rule.get("status") == "active"}
    if set(occurrences) != active:
        raise CheckError(f"shared registry/source rule mismatch: {label}")


def rule_records(
    payload: dict[str, object], label: str
) -> dict[str, tuple[tuple[object, ...], str]]:
    rules = payload.get("rules")
    if not isinstance(rules, list):
        raise CheckError(f"registry rules must be a list: {label}")
    records: dict[str, tuple[tuple[object, ...], str]] = {}
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            raise CheckError(f"invalid registry entry: {label}")
        rule_id = rule["id"]
        identity = tuple(rule.get(field) for field in ("name", "level", "scope", "statement"))
        status = rule.get("status")
        if (
            rule_id in records
            or not all(isinstance(value, str) and value for value in identity)
            or not isinstance(status, str)
            or status not in LEGAL_STATUS_TRANSITIONS
        ):
            raise CheckError(f"invalid historical rule identity: {rule_id}")
        records[rule_id] = (identity, status)
    return records


def legacy_rule_records(
    payload: dict[str, object], label: str, sources: dict[str, str]
) -> dict[str, tuple[tuple[object, ...], str]]:
    rules = payload.get("rules")
    if not isinstance(rules, list):
        raise CheckError(f"legacy registry rules must be a list: {label}")
    declarations: dict[str, tuple[tuple[str, str, str], str]] = {}
    stack_projections: dict[str, frozenset[str]] = {}
    for source_path, text in sources.items():
        source_name = source_path.rsplit("/", 1)[-1]
        local_seen: set[str] = set()
        for rule_id, level, name, statement in DECLARATION.findall(text):
            if rule_id in local_seen:
                raise CheckError(f"duplicate legacy rule declaration: {rule_id}")
            local_seen.add(rule_id)
            declaration = (level, name, statement)
            previous = declarations.get(rule_id)
            if previous is not None:
                previous_declaration, previous_source = previous
                if previous_declaration != declaration:
                    raise CheckError(f"conflicting legacy rule declaration: {rule_id}")
                if not (source_name.startswith("20-stack-") and previous_source == source_name):
                    raise CheckError(f"duplicate legacy rule declaration: {rule_id}")
            declarations[rule_id] = (declaration, source_name)
        if source_name.startswith("20-stack-"):
            projection = frozenset(local_seen)
            previous_projection = stack_projections.get(source_name)
            if previous_projection is not None and previous_projection != projection:
                raise CheckError(f"legacy stack projection mismatch: {source_path}")
            stack_projections[source_name] = projection
    records: dict[str, tuple[tuple[object, ...], str]] = {}
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            raise CheckError(f"invalid legacy registry entry: {label}")
        rule_id = rule["id"]
        level = rule.get("level")
        scope = rule.get("scope")
        declaration_record = declarations.get(rule_id)
        if (
            rule_id in records
            or not RULE_ID.fullmatch(rule_id)
            or level not in LEVELS
            or not isinstance(scope, str)
            or not scope
            or declaration_record is None
            or declaration_record[0][0] != level
        ):
            raise CheckError(f"invalid legacy rule identity: {rule_id}")
        declaration, _source_name = declaration_record
        _, name, statement = declaration
        records[rule_id] = ((name, level, scope, statement), "active")
    if set(declarations) != set(records):
        raise CheckError(f"legacy registry/source rule mismatch: {label}")
    return records


def read_git_blob(process: subprocess.Popen[bytes], spec: str) -> bytes | None:
    if process.stdin is None or process.stdout is None:
        raise CheckError("cannot inspect registry object stream")
    process.stdin.write(f"{spec}\n".encode())
    process.stdin.flush()
    header = process.stdout.readline().rstrip(b"\n")
    if header.endswith(b" missing"):
        return None
    parts = header.split()
    if len(parts) != 3 or parts[1] != b"blob" or not parts[2].isdigit():
        raise CheckError(f"invalid registry object response: {spec}")
    size = int(parts[2])
    if size > MAX_REGISTRY_BYTES:
        raise CheckError(f"historical registry exceeds size limit: {spec}")
    body = process.stdout.read(size)
    if len(body) != size or process.stdout.read(1) != b"\n":
        raise CheckError(f"incomplete registry object response: {spec}")
    return body


def validate_historical_identities() -> None:
    registry_paths = [ROOT / ".rulesync" / "shared-rules.json", ROOT / ".rulesync" / "rules.json"]
    registry_paths += sorted((ROOT / ".rulesync" / "nested").glob("**/rules.json"))
    current: dict[str, tuple[tuple[object, ...], str]] = {}
    for registry_path in registry_paths:
        if not registry_path.is_file():
            continue
        relative = registry_path.relative_to(ROOT).as_posix()
        for rule_id, record in rule_records(load_json(registry_path), relative).items():
            if rule_id in current:
                raise CheckError(f"rule id appears in multiple registries: {rule_id}")
            current[rule_id] = record

    base_sha = os.environ.get("MISOTO_HARNESS_BASE_SHA")
    if not base_sha:
        if os.environ.get("GITHUB_ACTIONS") == "true":
            raise CheckError("hosted history baseline is unavailable")
        return
    if not re.fullmatch(r"[0-9a-f]{40}", base_sha):
        raise CheckError("invalid hosted history baseline")
    resolved = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", f"{base_sha}^{{commit}}"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if resolved.returncode != 0:
        raise CheckError("hosted history baseline is unavailable")
    ancestry = subprocess.run(
        ["git", "merge-base", "--is-ancestor", base_sha, "HEAD"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if ancestry.returncode != 0:
        raise CheckError("hosted history baseline is not an ancestor of HEAD")

    graph = subprocess.run(
        [
            "git",
            "rev-list",
            "--full-history",
            "--topo-order",
            "--reverse",
            "--parents",
            "HEAD",
            "--",
            ".rulesync",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if graph.returncode != 0:
        raise CheckError("cannot inspect registry history")
    graph_rows = [line.split() for line in graph.stdout.splitlines()]
    if len(graph_rows) > MAX_HISTORY_COMMITS:
        raise CheckError("registry history exceeds commit limit")

    changed_paths = subprocess.run(
        ["git", "log", "--full-history", "--format=", "--name-only", "HEAD", "--", ".rulesync"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if changed_paths.returncode != 0:
        raise CheckError("cannot inspect registry path history")
    historical_paths = sorted(
        {
            path
            for path in changed_paths.stdout.splitlines()
            if path in {".rulesync/shared-rules.json", ".rulesync/rules.json"}
            or (path.startswith(".rulesync/nested/") and path.endswith("/rules.json"))
        }
    )
    historical_source_paths = sorted(
        {
            path
            for path in changed_paths.stdout.splitlines()
            if (
                path.startswith(".rulesync/rules/")
                and (
                    path.rsplit("/", 1)[-1] == "50-project.md"
                    or re.fullmatch(r"[12]0-[^/]+\.md", path.rsplit("/", 1)[-1]) is not None
                )
            )
            or (
                path.startswith(".rulesync/nested/")
                and (
                    path.rsplit("/", 1)[-1] == "50-project.md"
                    or path.rsplit("/", 1)[-1].startswith("20-stack-")
                )
            )
        }
    )
    all_history_paths = historical_paths + historical_source_paths
    if len(all_history_paths) > MAX_HISTORY_PATHS:
        raise CheckError("registry history exceeds path limit")
    if len(graph_rows) * len(all_history_paths) > MAX_HISTORY_OBJECTS:
        raise CheckError("registry history exceeds object limit")

    historical_identities: dict[str, tuple[object, ...]] = {}
    lifecycle_states: dict[str, dict[str, str]] = {}
    schema_states: dict[str, set[str]] = {}
    projection_states: dict[str, bool] = {}
    cat_file = subprocess.Popen(
        ["git", "cat-file", "--batch"],
        cwd=ROOT,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    stream_complete = False
    history_bytes = 0
    try:
        for row in graph_rows:
            commit, *parents = row
            inherited_statuses: dict[str, set[str]] = {}
            inherited_v2: set[str] = set()
            inherited_projections = False
            for parent in parents:
                if parent not in lifecycle_states:
                    raise CheckError("invalid registry history graph")
                for rule_id, status in lifecycle_states[parent].items():
                    inherited_statuses.setdefault(rule_id, set()).add(status)
                inherited_v2.update(schema_states[parent])
                inherited_projections = inherited_projections or projection_states[parent]

            snapshot_records: dict[str, tuple[tuple[object, ...], str]] = {}
            snapshot_locations: dict[str, str] = {}
            source_texts: dict[str, str] = {}
            for relative in historical_source_paths:
                body = read_git_blob(cat_file, f"{commit}:{relative}")
                if body is None:
                    continue
                history_bytes += len(body)
                if history_bytes > MAX_HISTORY_BYTES:
                    raise CheckError("registry history exceeds byte limit")
                try:
                    source_texts[relative] = body.decode("utf-8")
                except UnicodeDecodeError as error:
                    raise CheckError(f"historical rule source is not UTF-8: {relative}") from error
            for relative in historical_paths:
                body = read_git_blob(cat_file, f"{commit}:{relative}")
                if body is None:
                    continue
                history_bytes += len(body)
                if history_bytes > MAX_HISTORY_BYTES:
                    raise CheckError("registry history exceeds byte limit")
                try:
                    text = body.decode("utf-8")
                except UnicodeDecodeError as error:
                    raise CheckError(f"historical registry is not UTF-8: {relative}") from error
                payload = parse_json(text, f"{commit}:{relative}")
                schema_version = payload.get("schemaVersion")
                if schema_version != 2:
                    if schema_version not in {None, 1} or not isinstance(
                        payload.get("rules"), list
                    ):
                        raise CheckError(f"unsupported historical registry schema: {relative}")
                    if relative in inherited_v2:
                        raise CheckError(f"historical registry schema regressed: {relative}")
                    if relative == ".rulesync/shared-rules.json":
                        legacy_sources = {
                            path: text
                            for path, text in source_texts.items()
                            if (
                                path.startswith(".rulesync/rules/")
                                and path.rsplit("/", 1)[-1].startswith(("10-core-", "20-stack-"))
                            )
                            or (
                                path.startswith(".rulesync/nested/")
                                and path.rsplit("/", 1)[-1].startswith("20-stack-")
                            )
                        }
                    elif relative == ".rulesync/rules.json":
                        legacy_sources = {
                            ".rulesync/rules/50-project.md": source_texts.get(
                                ".rulesync/rules/50-project.md", ""
                            )
                        }
                    else:
                        source_path = f"{relative.rsplit('/', 1)[0]}/50-project.md"
                        legacy_sources = {source_path: source_texts.get(source_path, "")}
                    historical = legacy_rule_records(payload, relative, legacy_sources)
                else:
                    inherited_v2.add(relative)
                    if relative == ".rulesync/shared-rules.json":
                        rules = payload.get("rules")
                        registered = (
                            {
                                rule["id"]: rule
                                for rule in rules
                                if isinstance(rule, dict) and isinstance(rule.get("id"), str)
                            }
                            if isinstance(rules, list)
                            else {}
                        )
                        if "projections" in payload:
                            validate_shared_projections(
                                payload, registered, source_texts, f"{commit}:{relative}"
                            )
                            inherited_projections = True
                        elif inherited_projections:
                            raise CheckError("historical shared projection contract regressed")
                    historical = rule_records(payload, relative)
                for rule_id, record in historical.items():
                    previous_location = snapshot_locations.get(rule_id)
                    if previous_location is not None and previous_location != relative:
                        raise CheckError(
                            f"rule id appears in multiple historical registries: {rule_id}"
                        )
                    snapshot_locations[rule_id] = relative
                    snapshot_records[rule_id] = record

            missing_rules = inherited_statuses.keys() - snapshot_records.keys()
            if missing_rules:
                raise CheckError(f"historical rule id is missing: {min(missing_rules)}")
            commit_statuses: dict[str, str] = {}
            for rule_id, (identity, status) in snapshot_records.items():
                previous_identity = historical_identities.get(rule_id)
                if previous_identity is not None and previous_identity != identity:
                    raise CheckError(f"historical rule identity changed: {rule_id}")
                historical_identities[rule_id] = identity
                if any(
                    status not in LEGAL_STATUS_TRANSITIONS[previous_status]
                    for previous_status in inherited_statuses.get(rule_id, set())
                ):
                    raise CheckError(f"historical rule lifecycle regressed: {rule_id}")
                commit_statuses[rule_id] = status

            lifecycle_states[commit] = commit_statuses
            schema_states[commit] = inherited_v2
            projection_states[commit] = inherited_projections
        stream_complete = True
    finally:
        if cat_file.stdin is not None and not cat_file.stdin.closed:
            cat_file.stdin.close()
        if not stream_complete and cat_file.poll() is None:
            cat_file.terminate()
        if cat_file.wait() != 0 and stream_complete:
            raise CheckError("cannot inspect registry object stream")

    missing_current = historical_identities.keys() - current.keys()
    if missing_current:
        raise CheckError(f"historical rule id is missing: {min(missing_current)}")
    tip_statuses = lifecycle_states[graph_rows[-1][0]] if graph_rows else {}
    for rule_id, (current_identity, current_status) in current.items():
        historical_identity = historical_identities.get(rule_id)
        if historical_identity is not None and current_identity != historical_identity:
            raise CheckError(f"historical rule identity changed: {rule_id}")
        previous_status = tip_statuses.get(rule_id)
        if (
            previous_status is not None
            and current_status not in LEGAL_STATUS_TRANSITIONS[previous_status]
        ):
            raise CheckError(f"historical rule lifecycle regressed: {rule_id}")


def validate_manifest() -> None:
    manifest_path = ROOT / ".rulesync" / "managed-files.json"
    payload = load_json(manifest_path)
    if payload.get("schemaVersion") != 2 or not isinstance(payload.get("files"), list):
        raise CheckError("invalid managed-file manifest")
    paths: set[str] = set()
    for entry in payload["files"]:
        if not isinstance(entry, dict):
            raise CheckError("invalid managed-file entry")
        relative = entry.get("path")
        expected_hash = entry.get("sha256")
        if not isinstance(relative, str) or relative in paths:
            raise CheckError("invalid or duplicate managed-file path")
        path = (ROOT / relative).resolve()
        if not path.is_relative_to(ROOT) or not path.is_file():
            raise CheckError(f"missing or unsafe managed file: {relative}")
        data = path.read_bytes()
        if hashlib.sha256(data).hexdigest() != expected_hash:
            raise CheckError(f"managed-file hash mismatch: {relative}")
        if MARKER.encode() not in data:
            raise CheckError(f"managed-file marker missing: {relative}")
        paths.add(relative)
    required = {
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        "rulesync.jsonc",
        "rulesync.lock.json",
        ".rulesync/harness-check.py",
        ".rulesync/shared-rules.json",
        ".github/workflows/misoto-harness.yml",
    }
    if not required.issubset(paths):
        raise CheckError("required managed files are missing from the manifest")


def validate_adapters() -> None:
    if "@AGENTS.md" not in (ROOT / "CLAUDE.md").read_text(encoding="utf-8"):
        raise CheckError("Claude adapter does not import AGENTS.md")
    if "@./AGENTS.md" not in (ROOT / "GEMINI.md").read_text(encoding="utf-8"):
        raise CheckError("Gemini adapter does not import AGENTS.md")
    nested_root = ROOT / ".rulesync" / "nested"
    if nested_root.is_dir():
        for registry in sorted(nested_root.glob("**/rules.json")):
            relative = registry.parent.relative_to(nested_root)
            target = ROOT / relative
            validate_contract(registry, registry.parent / "50-project.md", "nested")
            if "@AGENTS.md" not in (target / "CLAUDE.md").read_text(encoding="utf-8"):
                raise CheckError(f"nested Claude adapter mismatch: {relative}")
            if "@./AGENTS.md" not in (target / "GEMINI.md").read_text(encoding="utf-8"):
                raise CheckError(f"nested Gemini adapter mismatch: {relative}")


def main() -> int:
    try:
        validate_contract(
            ROOT / ".rulesync" / "rules.json",
            ROOT / ".rulesync" / "rules" / "50-project.md",
            "project",
        )
        validate_shared_contract()
        validate_historical_identities()
        validate_manifest()
        validate_adapters()
    except (CheckError, OSError, json.JSONDecodeError) as error:
        print(f"harness-check: {error}", file=sys.stderr)
        return 1
    print("harness-check: clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
