#!/usr/bin/env python3
# Generated by Misoto Harness; DO NOT EDIT.
"""Self-contained validation for a public Harness project snapshot."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
RULE_ID = re.compile(r"^(?:HAR|[A-Z][A-Z0-9]{1,11})-[A-Z][A-Z0-9]{1,11}-\d{3}$")
DECLARATION = re.compile(r"(?:\*\*)?\[([^\]\n]+)\]\s+(MUST|SHOULD|MAY)\b")
LEVELS = {"MUST", "SHOULD", "MAY"}
ENFORCEMENTS = {"test", "lint", "review", "runtime"}
MARKER = "Generated by Misoto Harness; DO NOT EDIT."


class CheckError(ValueError):
    pass


def load_json(path: Path) -> dict[str, object]:
    def reject_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
        result: dict[str, object] = {}
        for key, value in pairs:
            if key in result:
                raise CheckError(f"duplicate JSON key in {path}: {key}")
            result[key] = value
        return result

    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=reject_duplicates)


def source_scope(text: str, path: Path) -> str:
    if not text.startswith("---\n") or "\n---\n" not in text[4:]:
        raise CheckError(f"invalid source frontmatter: {path}")
    frontmatter = text[4 : text.find("\n---\n", 4)]
    values = [
        line.partition(":")[2].strip()
        for line in frontmatter.splitlines()
        if line.startswith("scope:")
    ]
    if len(values) != 1:
        raise CheckError(f"source requires one scope: {path}")
    return values[0]


def validate_contract(registry_path: Path, source_path: Path, expected_scope: str) -> None:
    payload = load_json(registry_path)
    rules = payload.get("rules")
    if not isinstance(rules, list):
        raise CheckError(f"registry rules must be a list: {registry_path}")
    registered: dict[str, dict[str, object]] = {}
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            raise CheckError(f"invalid registry entry: {registry_path}")
        rule_id = rule["id"]
        if not RULE_ID.fullmatch(rule_id) or rule_id in registered:
            raise CheckError(f"invalid or duplicate rule id: {rule_id}")
        if rule.get("level") not in LEVELS or rule.get("scope") != expected_scope:
            raise CheckError(f"registry metadata mismatch: {rule_id}")
        owner = rule.get("owner")
        sources = rule.get("sources")
        if (
            not isinstance(owner, str)
            or not owner
            or not isinstance(sources, list)
            or not sources
            or not all(isinstance(source, str) and source for source in sources)
            or rule.get("enforcement") not in ENFORCEMENTS
        ):
            raise CheckError(f"incomplete registry entry: {rule_id}")
        registered[rule_id] = rule

    text = source_path.read_text(encoding="utf-8")
    if source_scope(text, source_path) != expected_scope:
        raise CheckError(f"source scope mismatch: {source_path}")
    declarations = DECLARATION.findall(text)
    seen: dict[str, str] = {}
    for rule_id, level in declarations:
        if not RULE_ID.fullmatch(rule_id) or rule_id in seen:
            raise CheckError(f"invalid or duplicate source rule id: {rule_id}")
        seen[rule_id] = level
    if set(seen) != set(registered):
        raise CheckError(f"registry/source rule mismatch: {registry_path}")
    for rule_id, level in seen.items():
        if registered[rule_id]["level"] != level:
            raise CheckError(f"rule level mismatch: {rule_id}")


def validate_shared_contract() -> None:
    registry_path = ROOT / ".rulesync" / "shared-rules.json"
    payload = load_json(registry_path)
    rules = payload.get("rules")
    if not isinstance(rules, list):
        raise CheckError("shared registry rules must be a list")
    registered: dict[str, dict[str, object]] = {}
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            raise CheckError("invalid shared registry entry")
        rule_id = rule["id"]
        owner = rule.get("owner")
        sources = rule.get("sources")
        if not RULE_ID.fullmatch(rule_id) or rule_id in registered:
            raise CheckError(f"invalid or duplicate shared rule id: {rule_id}")
        if rule.get("scope") not in {"core", "stack"} or rule.get("level") not in LEVELS:
            raise CheckError(f"shared registry metadata mismatch: {rule_id}")
        if (
            not isinstance(owner, str)
            or not owner
            or not isinstance(sources, list)
            or not sources
            or not all(isinstance(source, str) and source for source in sources)
            or rule.get("enforcement") not in ENFORCEMENTS
        ):
            raise CheckError(f"incomplete shared registry entry: {rule_id}")
        registered[rule_id] = rule
    seen: set[str] = set()
    sources = sorted((ROOT / ".rulesync" / "rules").glob("[12]0-*.md"))
    sources += sorted((ROOT / ".rulesync" / "nested").glob("**/20-stack-*.md"))
    for path in sources:
        expected_scope = "core" if path.name.startswith("10-core-") else "stack"
        text = path.read_text(encoding="utf-8")
        if source_scope(text, path) != expected_scope:
            raise CheckError(f"shared source scope mismatch: {path}")
        local_seen: set[str] = set()
        for rule_id, level in DECLARATION.findall(text):
            if not RULE_ID.fullmatch(rule_id) or rule_id in local_seen:
                raise CheckError(f"invalid or duplicate shared source rule id: {rule_id}")
            rule = registered.get(rule_id)
            if rule is None or rule.get("scope") != expected_scope or rule.get("level") != level:
                raise CheckError(f"shared registry mismatch: {rule_id}")
            local_seen.add(rule_id)
            seen.add(rule_id)
    if seen != set(registered):
        raise CheckError("shared registry/source rule mismatch")


def validate_manifest() -> None:
    manifest_path = ROOT / ".rulesync" / "managed-files.json"
    payload = load_json(manifest_path)
    if payload.get("schemaVersion") != 2 or not isinstance(payload.get("files"), list):
        raise CheckError("invalid managed-file manifest")
    paths: set[str] = set()
    for entry in payload["files"]:
        if not isinstance(entry, dict):
            raise CheckError("invalid managed-file entry")
        relative = entry.get("path")
        expected_hash = entry.get("sha256")
        if not isinstance(relative, str) or relative in paths:
            raise CheckError("invalid or duplicate managed-file path")
        path = (ROOT / relative).resolve()
        if not path.is_relative_to(ROOT) or not path.is_file():
            raise CheckError(f"missing or unsafe managed file: {relative}")
        data = path.read_bytes()
        if hashlib.sha256(data).hexdigest() != expected_hash:
            raise CheckError(f"managed-file hash mismatch: {relative}")
        if MARKER.encode() not in data:
            raise CheckError(f"managed-file marker missing: {relative}")
        paths.add(relative)
    required = {
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        "rulesync.jsonc",
        "rulesync.lock.json",
        ".rulesync/harness-check.py",
        ".rulesync/shared-rules.json",
        ".github/workflows/misoto-harness.yml",
    }
    if not required.issubset(paths):
        raise CheckError("required managed files are missing from the manifest")


def validate_adapters() -> None:
    if "@AGENTS.md" not in (ROOT / "CLAUDE.md").read_text(encoding="utf-8"):
        raise CheckError("Claude adapter does not import AGENTS.md")
    if "@./AGENTS.md" not in (ROOT / "GEMINI.md").read_text(encoding="utf-8"):
        raise CheckError("Gemini adapter does not import AGENTS.md")
    nested_root = ROOT / ".rulesync" / "nested"
    if nested_root.is_dir():
        for registry in sorted(nested_root.glob("**/rules.json")):
            relative = registry.parent.relative_to(nested_root)
            target = ROOT / relative
            validate_contract(registry, registry.parent / "50-project.md", "nested")
            if "@AGENTS.md" not in (target / "CLAUDE.md").read_text(encoding="utf-8"):
                raise CheckError(f"nested Claude adapter mismatch: {relative}")
            if "@./AGENTS.md" not in (target / "GEMINI.md").read_text(encoding="utf-8"):
                raise CheckError(f"nested Gemini adapter mismatch: {relative}")


def main() -> int:
    try:
        validate_contract(
            ROOT / ".rulesync" / "rules.json",
            ROOT / ".rulesync" / "rules" / "50-project.md",
            "project",
        )
        validate_shared_contract()
        validate_manifest()
        validate_adapters()
    except (CheckError, OSError, json.JSONDecodeError) as error:
        print(f"harness-check: {error}", file=sys.stderr)
        return 1
    print("harness-check: clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
